version: '2'
services:
      
  ogamma-logger:
    image: 'ogamma/logger:3.0.0'
    restart: always
    
    environment:    
# By default configuration file ./data/config.json is used. Can be changed by environment variable:    
      - OVL_CONFIG_FILE=./data/config.json
# Do not use default credentials production!
      - OVL_USER_ID=admin
      - OVL_USER_PASSWORD=password
    
    ports:
      - '4880:4880'
    hostname: ogamma-logger
    volumes:
      - './data:/home/ogamma/logger/data'

    networks:
      - ogamma-logger
 
networks:
  ogamma-logger: null

