version: '3'
services:

#InfluxDB version 2.0.3
  influxdb2.0.3:
    image: quay.io/influxdb/influxdb:v2.0.3
    command: >
      bash -c "chmod 774 /opt/start_and_init.sh && /opt/start_and_init.sh"
    volumes:
      - 'ogamma-logger-influxdb2.0.3-data:/root/.influxdbv2'
      - './opt2.0.3:/opt'
    ports:
      - '8016:8086'
    networks:
      - ogamma-logger
networks:
  ogamma-logger: null
volumes:
  ogamma-logger-influxdb2.0.3-data: {}
