version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    ports:
      - '2181:2181'
    hostname: zookeeper
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ogamma-logger
      
  kafka:
    image: 'bitnami/kafka:2.6.0'
    ports:
      - '9092:9092'
      - '29092:29092'
    hostname: kafka
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,SASL_PLAINTEXT://kafka:29092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,SASL_PLAINTEXT://kafka:29092
    depends_on:
      - zookeeper
    networks:
      - ogamma-logger

networks:
  ogamma-logger: null
  
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local