version: '3'
services:
# MQTT Broker Eclipse Mosquitto   
  mqtt:
    image: 'eclipse-mosquitto'
    ports:
      - '1883:1883'
      - '9001:9001'
    networks:
      - ogamma-logger    
      
networks:
  ogamma-logger: null

