
services:
# MQTT Broker Eclipse Mosquitto   
  mqtt:
    image: 'eclipse-mosquitto:latest'
    ports:
      - '1883:1883'
      - '9001:9001'
    networks:
      - ogamma-logger
    volumes:
      - './mqtt:/mosquitto/config'
networks:
  ogamma-logger: null
