version: '3'
services:
# Microsoft SQL Server
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04'
    ports:
      - '1433:1433'
    hostname: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ogamma_123 #TODO
    networks:
      - ogamma-logger      
      
networks:
  ogamma-logger: null

