version: '3'
services:
# Demo OPC UA Server
  opcplc:
    image: 'mcr.microsoft.com/iotedge/opc-plc:1.0.1-linux-amd64'
    hostname: opcplc
    ports:
      - '50000:50000'
    command: '--aa'
    networks:
      - ogamma-logger

networks:
  ogamma-logger: null

