version: '3'
services:
 # Example of the second instance configuration:
 ogamma-logger2:
   image: 'ogamma/logger:2.1.0'
   environment:
    - OVL_CONFIG_FILE=./data/config2.json
   ports:
    - '4881:4881'
   hostname: ogamma-logger
   volumes:
    - './data:/home/ogamma/logger/data'
   networks:
    - ogamma-logger
   extra_hosts:
    - '${HOST_NAME:-opcuaserver.com}:${HOST_IP_ADDRESS:-75.152.105.54}'
networks:
  ogamma-logger: null
volumes:
